name: Build the Python Container
on:
  workflow_call:
    inputs:
      publish:
        description: |
          Push the container image to Docker Hub.
          This should be set to true if you want to push the image.
        required: true
        type: boolean
        default: false
      python-version:
        description: |
          Python version to use for the container building process. Because we are using chainguard, this version should be the latest minor version of Python.
          At the time of writing the workflow, the version is 3.13. Link: https://images.chainguard.dev/directory/image/python/versions
        required: true
        type: string
    secrets:
      DOCKER_HUB_TOKEN:
        description: |
          Docker Hub token for pushing the container image.
          This token should have write access to the repository.
        required: true

jobs:
  build-container:
    name: Build the Python Container
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: read
    steps:
      ## Set an Initial Step
      - name: Workshop Initial Step
        run: |
          echo "Hello World!"
